### ISSUE TITLE
broken tcadmin

### ISSUE THREAD

**Issue by numpty9989** [Alexr03/TCAdminBatchSteamUpdate#2]
hi.. I installed this plugin via the install plugin button and when refreshed my tcadmin to look at the new feature and begin setting it up to my tcadmin now looks like this https://i.imgur.com/0zcwIz8.png please help my panel is useless until its fixed.. and the only thing touched file wise was installing this plugin

**Comment by Alexr03** [comment]
Hi, Open a ticket with Luis on TCAdmin.com - I don't modify any pages so i'm not sure why that happens.
Also - Try the NexT theme, that may fix it.

**Comment by numpty9989** [comment]
Happened on all themes including next.. tcadmin ficed it

**Comment by Alexr03** [comment]
Good to hear its fixed
